Repository BCG-X-Official/sklearndf, pull requests merged in 2021-03, with the labels that each got.

#135 TEST: add unit test for docstrings
  condabuild/meta.yaml
  pyproject.toml
  src/sklearndf/_sklearndf.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/test_docs.py
  tox.ini
Labels: CI/CD, documentation

#142 TEST: rename validate_docstrings() to validate_doc()
  test/test/test_docs.py
Labels: refactor

#139 FIX: support "passthrough" column transformer
  src/sklearndf/transformation/_transformation.py
Labels: bug

#141 API: remove the experimental 'feature_sequence' option from class LearnerPipelineDF
  src/sklearndf/pipeline/_learner_pipeline.py
Labels: enhancement

#140 FIX: support "passthrough" column transformer
  src/sklearndf/transformation/wrapper/_wrapper.py
Labels: bug

#134 FIX: OneHotEncoderDF bug for drop argument usage
  src/sklearndf/transformation/_transformation.py
  test/test/sklearndf/transformation/test_imputers.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: bug

#143 DOC: add release notes for 1.0.2
  .idea/sklearndf.iml
  README.rst
  RELEASE_NOTES.rst
  sphinx/source/.gitignore
  sphinx/source/api_landing.rst
  sphinx/source/index.rst
Labels: documentation

#145 BUILD: update azure-pipelines.yml for release workflow
  azure-pipelines.yml
  test/test/sklearndf/test_package_version.py
Labels: CI/CD

#146 TEST: run encoder test with 'if_binary' only from sklearn 0.23
  test/test/sklearndf/transformation/test_transformation.py
Labels: bug

#148 BUILD: set to version 1.0.2rc0
  src/sklearndf/_version.py
Labels: CI/CD

#147 DOCS: add pre-commit hook instructions to contribution guide
  sphinx/source/contribution_guide.rst
Labels: documentation

#149 BUILD: bugfix in azure-pipelines.yml for version check
  azure-pipelines.yml
Labels: CI/CD, bug

#150 RELEASE: sklearndf 1.0.2rc0
  .idea/sklearndf.iml
  LICENSE
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  pyproject.toml
  sphinx/source/.gitignore
  sphinx/source/api_landing.rst
  sphinx/source/contribution_guide.rst
  sphinx/source/faqs.rst
  sphinx/source/index.rst
  src/sklearndf/__init__.py
  src/sklearndf/_version.py
  src/sklearndf/_wrapper.py
  src/sklearndf/transformation/_transformation.py
  test/test/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_package_version.py
  test/test/sklearndf/transformation/test_imputers.py
  test/test/sklearndf/transformation/test_transformation.py
  tox.ini
Labels: release

#151 BUILD: correct the working directory & deps for PyPi upload
  azure-pipelines.yml
Labels: CI/CD, bug

#152 BUILD: prepare for 1.0.2 release
  pyproject.toml
  src/sklearndf/_version.py
  test/test/sklearndf/test_package_version.py
Labels: release

#153 BUILD: update flake8 to v3.9.0
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  src/sklearndf/__init__.py
Labels: CI/CD

#144 FIX: port fix for OneHotEncoderWrapperDF to sklearn 1.1.x
  src/sklearndf/transformation/wrapper/_wrapper.py
Labels: bug

#154 FIX: allow imported definitions in AllTracker for sklearn wrapper classes
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/extra/_extra.py
Labels: bug, enhancement, sequential

#155 RELEASE: sklearndf 1.0.2
  .pre-commit-config.yaml
  README.rst
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/sklearndf/__init__.py
  src/sklearndf/_version.py
  test/test/sklearndf/test_package_version.py
Labels: release

#158 BUILD: support pytools 1.1.0rc0 in min build of sklearndf
  pyproject.toml
Labels: CI/CD

#159 BUILD: prepare for sklearndf 1.1.0 release
  RELEASE_NOTES.rst
  pyproject.toml
  src/sklearndf/_version.py
Labels: CI/CD

#160 BUILD: release sklearndf 1.1.0
  RELEASE_NOTES.rst
  pyproject.toml
  src/sklearndf/_version.py
Labels: release

#163 DOC: set doc link in readme to point to sklearndf
  README.rst
Labels: documentation
