Repository BCG-X-Official/sklearndf, pull requests merged in 2021-02, with the labels that each got.

#120 BUILD: bugfix the detection of changes to build files
  azure-pipelines.yml
Labels: CI/CD, bug

#121 BUILD: do not run nightly builds on weekends
  azure-pipelines.yml
Labels: CI/CD

#119 BUILD: align build requirements pyproject.toml/meta.yaml/tox.ini & across repos
  condabuild/meta.yaml
  pyproject.toml
  test/test/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  tox.ini
Labels: CI/CD

#125 BUILD: allow any version of pytools 1.0 in sklearndf matrix builds
  pyproject.toml
Labels: CI/CD

#123 BUILD: eliminate unconstrained build from pipeline
  azure-pipelines.yml
Labels: CI/CD, bug

#126 BUILD: add support for numpy 1.20
  environment.yml
  pyproject.toml
  src/sklearndf/__init__.py
Labels: CI/CD

#127 BUILD: update environment.yml
  azure-pipelines.yml
  environment.yml
  pyproject.toml
Labels: CI/CD

#128 BUILD: update veracode scan version to point to BuildID
  azure-pipelines.yml
Labels: CI/CD

#129 BUILD: optimize conda build config
  condabuild/meta.yaml
Labels: CI/CD

#130 fix a syntax error introduced to a bash script in the pipeline
  azure-pipelines.yml
Labels: CI/CD, bug

#131 DOC: restore azure pipelines badge
  README.rst
Labels: documentation

#132 BUILD: use regular pytest & pytest-cov, run pytest nightly
  azure-pipelines.yml
Labels: CI/CD

#136 FIX: downgrade scipy to 1.5.* in environment.yml
  environment.yml
  pyproject.toml
Labels: CI/CD, bug

#138 BUILD: support pytools from 1.0.2rc0
  pyproject.toml
Labels: CI/CD, bug

#137 change version to 1.1.0rc0
  src/sklearndf/_version.py
Labels: CI/CD
