Repository BCG-X-Official/sklearndf, pull requests merged in 2021-01, with the labels that each got.

#96 Bugfix/python3.9 compatibility
  src/sklearndf/_sklearndf.py
Labels: bug

#98 import from numpy.testing instead of sklearn.utils.testing
  test/test/sklearndf/pipeline/test_pipeline_df.py
Labels: bug

#99 sklearn 0.24 currently not supported
  pyproject.toml
Labels: bug

#100 disallow scipy >=1.6, allow pandas 1.2.*, prefer joblib 1.0.*
  pyproject.toml
Labels: release

#104 rename branch 1.1 to 1.1.x
  azure-pipelines.yml
Labels: CI/CD

#102 update the environment.yml
  environment.yml
Labels: CI/CD

#107 BUG: create individual __init__ methods per wrapped estimator
  src/sklearndf/_wrapper.py
  test/test/sklearndf/test_base.py
Labels: bug

#108 BUG: do not mirror native estimator class attributes and protected members
  src/sklearndf/_wrapper.py
Labels: bug

#110 BUG: test for different estimator repr() depending on sklearn version
  test/test/sklearndf/test_base.py
Labels: bug

#106 Introduce factory functions to simplify the creation of ...DF estimators
  src/sklearndf/_wrapper.py
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/extra/_extra.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
Labels: enhancement, refactor

#111 API: expose the sklearndf wrapper API, allowing users to create their own augmented estimators
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/classification/wrapper/__init__.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/pipeline/wrapper/__init__.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/regression/wrapper/__init__.py
  src/sklearndf/regression/wrapper/_wrapper.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/_wrapper.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/transformation/wrapper/__init__.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_regression.py
Labels: enhancement

#113 REFACTOR: clean up wrapper code
  src/sklearndf/wrapper/_wrapper.py
Labels: refactor

#114 BUILD: add veracode static scan to nightly build pipeline
  azure-pipelines.yml
Labels: CI/CD

#116 BUILD: update version numbers
  sphinx/source/faqs.rst
  src/sklearndf/_version.py
Labels: CI/CD

#117 BUILD: bump version to 1.0.2
  pyproject.toml
  sphinx/source/faqs.rst
  src/sklearndf/_version.py
Labels: CI/CD

#118 BUILD: do not build and publish documentation in nightly builds
  azure-pipelines.yml
Labels: CI/CD, documentation
