Repository BCG-X-Official/sklearndf, pull requests merged in 2022-07, with the labels that each got.

#215 API: support for xgboost
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  mypy.ini
  pyproject.toml
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/regression/extra/_extra.py
  test/test/test_docs.py
  tox.ini
Labels: API

#221 API: allow declaring DF classes in the __main__ module
  src/sklearndf/wrapper/_wrapper.py
Labels: API

#219 DOC: enable local sphinx builds
  .idea/sklearndf.iml
  azure-pipelines.yml
  environment.yml
  sphinx/.gitignore
  sphinx/make.py
  sphinx/source/.gitignore
  sphinx/source/_templates/autosummary.rst
  sphinx/source/api_landing.rst
  sphinx/source/conf.py
  sphinx/source/contribution_guide.rst
  sphinx/source/index.rst
Labels: documentation

#223 REFACTOR: set mypy mode to 'strict'
  mypy.ini
  src/sklearndf/__init__.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/_classification_v1_0.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/_regression_v1_0.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/regression/wrapper/_wrapper.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/_transformation_v0_24.py
  src/sklearndf/transformation/_transformation_v1_0.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_adapter.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/__init__.py
  test/test/conftest.py
  test/test/sklearndf/__init__.py
  test/test/sklearndf/pipeline/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_classification.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/test_meta_estimators.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_imputers.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: refactor

#222 REFACTOR: minor code tweaks prior to the 2.0 release
  .idea/sklearndf.iml
  mypy.ini
  src/sklearndf/__init__.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/_classification_v1_0.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/_regression_v1_0.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/regression/wrapper/_wrapper.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/_transformation_v0_24.py
  src/sklearndf/transformation/_transformation_v1_0.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_adapter.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/__init__.py
  test/test/conftest.py
  test/test/sklearndf/__init__.py
  test/test/sklearndf/pipeline/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_classification.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/test_meta_estimators.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_imputers.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: refactor

#224 API: rename ClustererDF to ClusterDF in line with scikit-learn's ClusterMixin
  src/sklearndf/_sklearndf.py
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/clustering/wrapper/_wrapper.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/pipeline/test_clustering_pipeline.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: API

#225 API: simplify DF wrapper declarations
  pyproject.toml
  sphinx/make.py
  sphinx/source/faqs.rst
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/_classification_v1_0.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/_regression_v1_0.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/regression/wrapper/_wrapper.py
  src/sklearndf/transformation/__init__.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/_transformation_v0_23.py
  src/sklearndf/transformation/_transformation_v0_24.py
  src/sklearndf/transformation/_transformation_v1_0.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_classification.py
Labels: API
