Repository BCG-X-Official/sklearndf, pull requests merged in 2022-02, with the labels that each got.

#199 BUILD: Add support for `mypy`
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  mypy.ini
  src/sklearndf/__init__.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/_classification_v0_23.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v0_22.py
  src/sklearndf/transformation/_transformation_v0_23.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_adapter.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/__init__.py
Labels: build

#197 API: introduce support for `partial_fit`
  RELEASE_NOTES.rst
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/wrapper/_wrapper.py
  test/test/sklearndf/test_classification.py
  test/test/sklearndf/test_regression.py
Labels: API

#205 BUILD: move __version__ to sklearndf.__init__ so flit can pick it up
  src/sklearndf/__init__.py
  src/sklearndf/_version.py
Labels: release

#206 BUILD: add `py.typed` file
  src/sklearndf/py.typed
Labels: build

#204 BUILD: release sklearndf 1.2.3
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  pyproject.toml
  sphinx/source/_templates/api_landing.rst
  src/sklearndf/__init__.py
  src/sklearndf/_version.py
Labels: release

#201 API: move `FeatureAgglomeration` to clusterers
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/clustering/wrapper/_wrapper.py
  src/sklearndf/regression/wrapper/_wrapper.py
  src/sklearndf/transformation/_transformation.py
  test/test/sklearndf/__init__.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: API

#200 API: remove `OutlierRemoverDF` and `lightgbm` dependency
  RELEASE_NOTES.rst
  condabuild/meta.yaml
  pyproject.toml
  sphinx/source/tutorial/sklearndf_tutorial.ipynb
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/regression/extra/__init__.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/transformation/extra/_extra.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: API

#207 BUILD: drop Python 3.6 support and enable Python 3.9
  README.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  pypi_description.rst
  pyproject.toml
  src/sklearndf/_version.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  tox.ini
Labels: build
