Repository BCG-X-Official/sklearndf, pull requests merged in 2022-09, with the labels that each got.

#229 FIX: wrap extra classifiers using `ClassifierWrapperDF`; add validation to ensure native classes are compatible with wrapper classes
  RELEASE_NOTES.rst
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/pipeline/test_classification_pipeline_df.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/pipeline/test_regression_pipeline_df.py
  test/test/sklearndf/test_base.py
Labels: bug

#230 REFACTOR: minor fixes and stability improvements for sklearndf 2.0.1
  RELEASE_NOTES.rst
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: bug, refactor

#232 FIX: support array-likes for parameter `drop` of `OneHotEncoderDF`
  RELEASE_NOTES.rst
  src/sklearndf/transformation/wrapper/_wrapper.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: bug, API

#233 BUILD: release sklearndf 2.0.1
  RELEASE_NOTES.rst
  azure-pipelines.yml
  pyproject.toml
  src/sklearndf/__init__.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/transformation/extra/_extra.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/__init__.py
  test/test/sklearndf/pipeline/test_classification_pipeline_df.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/pipeline/test_regression_pipeline_df.py
  test/test/sklearndf/test_base.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: release

#231 API: add support for scikit-learn 1.1
  README.rst
  RELEASE_NOTES.rst
Labels: API

#234 BUILD: Release sklearndf 2.1rc0
  .pre-commit-config.yaml
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/sklearndf/__init__.py
  src/sklearndf/_sklearn_version.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/clustering/__init__.py
  src/sklearndf/clustering/_clustering_v1_1.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/transformation/__init__.py
  src/sklearndf/transformation/_transformation_v1_1.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
  src/sklearndf/wrapper/numpy/_numpy.py
  src/sklearndf/wrapper/stacking/_stacking.py
  test/test/conftest.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: release

#235 BUILD: release sklearndf 2.1.0
  RELEASE_NOTES.rst
  azure-pipelines.yml
  src/sklearndf/__init__.py
Labels: release

#237 API: add support for scikit-learn 1.2
  src/sklearndf/_sklearn_version.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/test_classification.py
Labels: API

#238 API: add property `EstimatorDF.output_names_`
  RELEASE_NOTES.rst
  src/sklearndf/_sklearn_version.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
  src/sklearndf/wrapper/numpy/_numpy.py
  src/sklearndf/wrapper/stacking/_stacking.py
  test/test/sklearndf/test_classification.py
Labels: API

#240 BUILD: release sklearndf 2.2.dev0
  .pre-commit-config.yaml
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  sphinx/make.py
  src/sklearndf/__init__.py
  src/sklearndf/_sklearn_version.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/_classification.py
  src/sklearndf/classification/_classification_v0_22.py
  src/sklearndf/classification/extra/_extra.py
  src/sklearndf/clustering/_clustering.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/pipeline/_pipeline.py
  src/sklearndf/regression/_regression.py
  src/sklearndf/regression/_regression_v0_22.py
  src/sklearndf/regression/_regression_v0_23.py
  src/sklearndf/regression/_regression_v1_0.py
  src/sklearndf/regression/extra/_extra.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v1_0.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_wrapper.py
  src/sklearndf/wrapper/numpy/_numpy.py
  src/sklearndf/wrapper/stacking/_stacking.py
  test/test/sklearndf/test_classification.py
Labels: release

#236 FIX: use fitted attribute n_components_ to get PCA component count
  RELEASE_NOTES.rst
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
Labels: bug

#239 REFACTOR: replace `EstimatorDF.ensure_fitted()` with pytools `@fitted_only`
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/sklearndf/_sklearndf.py
  src/sklearndf/clustering/wrapper/_wrapper.py
  src/sklearndf/pipeline/_learner_pipeline.py
  src/sklearndf/wrapper/_wrapper.py
  src/sklearndf/wrapper/numpy/_numpy.py
  src/sklearndf/wrapper/stacking/_stacking.py
Labels: API
