Repository BCG-X-Official/sklearndf, pull requests merged in 2022-03, with the labels that each got.

#196 API: Add support for sklearn 1.0
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/sklearndf/__init__.py
  src/sklearndf/classification/__init__.py
  src/sklearndf/classification/_classification_v1_0.py
  src/sklearndf/regression/__init__.py
  src/sklearndf/regression/_regression_v1_0.py
  src/sklearndf/transformation/__init__.py
  src/sklearndf/transformation/_transformation.py
  src/sklearndf/transformation/_transformation_v1_0.py
  src/sklearndf/transformation/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/sklearndf/test_classification.py
  test/test/sklearndf/transformation/test_transformation.py
Labels: API

#210 BUILD: update black to v22.1
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  src/sklearndf/__init__.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/pipeline/wrapper/__init__.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/__init__.py
  test/test/sklearndf/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_classification.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_extra.py
Labels: build

#208 BUILD: consider pytools type hints in mypy checks
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  azure-pipelines.yml
  mypy.ini
  src/sklearndf/_sklearndf.py
  src/sklearndf/clustering/wrapper/_wrapper.py
  src/sklearndf/wrapper/_wrapper.py
Labels: build

#212 BUILD: release sklearndf 2.0.dev3
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  azure-pipelines.yml
  environment.yml
  mypy.ini
  src/sklearndf/__init__.py
  src/sklearndf/_sklearndf.py
  src/sklearndf/classification/wrapper/_wrapper.py
  src/sklearndf/clustering/wrapper/_wrapper.py
  src/sklearndf/pipeline/wrapper/__init__.py
  src/sklearndf/pipeline/wrapper/_wrapper.py
  src/sklearndf/wrapper/__init__.py
  src/sklearndf/wrapper/_wrapper.py
  test/test/__init__.py
  test/test/sklearndf/__init__.py
  test/test/sklearndf/pipeline/test_pipeline_df.py
  test/test/sklearndf/test_classification.py
  test/test/sklearndf/test_clustering.py
  test/test/sklearndf/test_regression.py
  test/test/sklearndf/test_sklearn_coverage.py
  test/test/sklearndf/transformation/test_extra.py
Labels: release
